title: My Portfolio
repository: NRLTing-git/nting.github.io
email: nrl.ting@gmail.com
subtitle: "Hello world!"
name: "Nico Rafael Ting"

author:
  name: "Nico Rafael Ting"
  avatar: "/assets/image/LinkedIn DP.jpg"
  bio: "Data scientist and cookies and cream enthusiast." 
  location: "Metro Manila, Philippines"
  links:
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/miguel-lorenzo-singian/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MiguelSingian"
    - label: "Email"
      icon: "fa fa-envelope"
      url: "mailto: migsingian@gmail.com"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://www.instagram.com/miguelsingian/"

footer:
  links:
      - label: "LinkedIn"
        icon: "fa-brands fa-linkedin"
        url: "https://www.linkedin.com/in/miguel-lorenzo-singian/"
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/MiguelSingian"
      - label: "Email"
        icon: "fa fa-envelope"
        url: "mailto: migsingian@gmail.com"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.25.0" 
# theme: minima
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-relative-links
  - jekyll-jupyter-notebook

