title: My Portfolio
repository: NRLTing-git/nting.github.io
email: nrl.ting@gmail.com
subtitle: "Hello world!"
name: "Nico Rafael Ting"

defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      show_date: true
      author_profile: true
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

author:
  name: "Miguel Singian"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Data scientist and cookies and cream enthusiast." 
  location: "Metro Manila, Philippines"
  links:
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/miguel-lorenzo-singian/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MiguelSingian"
    - label: "Email"
      icon: "fa fa-envelope"
      url: "mailto: migsingian@gmail.com"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://www.instagram.com/miguelsingian/"


# author:
#   name: "Nico Rafael Ting"
#   avatar: "assets/image/LinkedIn DP.jpg"
#   bio: "A Data Scientist in the making" 
#   location: "Taguig, Philippines"
#   links:
#     - label: "LinkedIn"
#       icon: "fa-brands fa-linkedin"
#       url: "https://www.linkedin.com/in/nico-rafael-ting-7b5985242/"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/NRLTing-git/my-projects"
#     - label: "Email"
#       icon: "fa fa-envelope"
#       url: "mailto: nrl.ting@gmail.com"

footer:
  links:
      - label: "LinkedIn"
        icon: "fa-brands fa-linkedin"
        url: "https://www.linkedin.com/in/nico-rafael-ting-7b5985242/"
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/NRLTing-git/my-projects"
      - label: "Email"
        icon: "fa fa-envelope"
        url: "mailto: nrl.ting@gmail.com"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.25.0" 
# theme: minima
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-relative-links
  - jekyll-jupyter-notebook

