title: My Portfolio
repository: NRLTing-git/nting.github.io
email: nrl.ting@gmail.com
subtitle: "Hello world!"
name: "Nico Rafael Ting"

author:
  name: "Nico Rafael Ting"
  avatar: "assets/image/LinkedIn DP.jpg"
  bio: "A Data Scientist in the making" 
  location: "Taguig, Philippines"
  links:
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/nico-rafael-ting-7b5985242/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NRLTing-git/my-projects"
    - label: "Email"
      icon: "fa fa-envelope"
      url: "mailto: nrl.ting@gmail.com"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://www.instagram.com/miguelsingian/"

footer:
  links:
      - label: "LinkedIn"
        icon: "fa-brands fa-linkedin"
        url: "https://www.linkedin.com/in/nico-rafael-ting-7b5985242/"
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/NRLTing-git/my-projects"
      - label: "Email"
        icon: "fa fa-envelope"
        url: "mailto: nrl.ting@gmail.com"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.25.0" 
# theme: minima
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-relative-links
  - jekyll-jupyter-notebook

